### ISSUE TITLE
Error using HusPos in Heroku

### ISSUE THREAD

**Issue by domenicosolazzo** [domenicosolazzo/jroc#3]
Error when using the tagger with statistical disambiguation on Heroku.

Error log:

       sh: 1: /app/The-Oslo-Bergen-Tagger/OBT-Stat/hunpos/hunpos-1.0-linux/hunpos-tag: not found
       /app/The-Oslo-Bergen-Tagger/OBT-Stat/lib/disambiguation_context.rb:21:in `initialize': Inconsistent token count in OBT and Hunpos data. (ArgumentError)
       from /app/The-Oslo-Bergen-Tagger/OBT-Stat/lib/disambiguator.rb:153:in `disambiguate'
       from /app/The-Oslo-Bergen-Tagger/OBT-Stat/lib/disambiguator.rb:153:in `new'
       from /app/modules/tagger/../../The-Oslo-Bergen-Tagger/OBT-Stat/bin/run_obt_stat.rb:29:in `run_disambiguator'
       from /app/modules/tagger/../../The-Oslo-Bergen-Tagger/OBT-Stat/bin/run_obt_stat.rb:107:in `<main>'

**Comment by domenicosolazzo** [comment]
Fixed!
